apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rocketchat.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rocketchat.name" . }}
    helm.sh/chart: {{ include "rocketchat.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.smtp.enabled }}
  mail-url: {{ printf "smtp://%s:%s@%s:%.0f" .Values.smtp.username .Values.smtp.password .Values.smtp.host .Values.smtp.port | b64enc | quote }}
{{- end }}
{{- if .Values.mongodb.auth.existingSecret }}
  {{- $fullname := include "rocketchat.mongodb.fullname" . -}}
  {{- $username := required "Please specify a MongoDB username" .Values.mongodb.auth.username }}
  {{- $rsName := .Values.mongodb.replicaSetName }}
  {{- $port := .Values.mongodb.service.port }}
  {{- $dbname := required "Please specify a MongoDB database" .Values.mongodb.auth.database }}
  mongo-uri: {{ printf "mongodb://%s:$MONGODB_DB_PASS@%s:%.0f/%s" $username $fullname $port $dbname | b64enc | quote }}
  mongo-oplog-uri: {{ printf "mongodb://root:$MONGODB_ROOT_PASS@%s:%.0f/local?replicaSet=%s&authSource=admin" $fullname $port $rsName | b64enc | quote }}
{{- else }}
  {{- $fullname := include "rocketchat.mongodb.fullname" . -}}
  {{- $username := required "Please specify a MongoDB username" .Values.mongodb.auth.username }}
  {{- $password := required "Please specify a MongoDB password" .Values.mongodb.auth.password }}
  {{- $rootPassword := required "Please specify a MongoDB Root password" .Values.mongodb.auth.rootPassword }}
  {{- $rsName := .Values.mongodb.replicaSetName }}
  {{- $port := .Values.mongodb.service.port }}
  {{- $dbname := required "Please specify a MongoDB database" .Values.mongodb.auth.database }}
  mongo-uri: {{ printf "mongodb://%s:%s@%s:%.0f/%s" $username $password $fullname $port $dbname | b64enc | quote }}
  mongo-oplog-uri: {{ printf "mongodb://root:%s@%s:%.0f/local?replicaSet=%s&authSource=admin" $rootPassword $fullname $port $rsName | b64enc | quote }}
{{- end }}
